name: picture
description: ç¾çœ‰

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_staggered_grid_view: ^0.2.4
  shared_preferences: ^0.4.3
  flutter_refresh: ^0.0.2
  flutter_swiper: ^1.1.4
  common_utils: ^1.0.9
  dio: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/logo.png
    - images/loading.jpg
    - images/avatar.jpg
    - images/user_default_avatar.png
    - images/user_avatar.png

    - images/auth_bottom_background.png


  fonts:
    - family: jianyuanti
      fonts:
        - asset: fonts/fun.zhexue.jianyuanti.ttf